# sage_setup: distribution = sagemath-environment
# Sage version information for Python scripts
# This file is auto-generated by the update-version script, do not edit!
version = '10.6.1.rc4'
date = '2025-06-30'
banner = 'passagemath version 10.6.1.rc4, Release Date: 2025-06-30'
